export const TOOLS = [
  {
    slug: 'multiple-choice',
    title: 'Multiple Choice',
    subtitle: 'Soal Pilihan Ganda',
    desc: 'Generate soal pilihan ganda otomatis berdasarkan materi, tingkat kelas, dan jumlah soal.',
    module: 'assessment',
    icon: 'clipboard-list',
    accent: 'emerald',
  },
  {
    slug: 'rubric',
    title: 'Rubric Generator',
    subtitle: 'Rubrik Penilaian',
    desc: 'Buat rubrik penilaian yang detail untuk berbagai jenis tugas dan aktivitas pembelajaran.',
    module: 'assessment',
    icon: 'layers',
    accent: 'emerald',
  },
  {
    slug: 'writing-feedback',
    title: 'Writing Feedback',
    subtitle: 'Umpan Balik Karangan',
    desc: 'Berikan umpan balik konstruktif untuk karangan/tulisan siswa secara otomatis.',
    module: 'assessment',
    icon: 'file-edit',
    accent: 'emerald',
  },
  {
    slug: 'worksheet',
    title: 'Worksheet Generator',
    subtitle: 'Lembar Kerja Siswa',
    desc: 'Buat lembar kerja siswa (LKS) yang terstruktur dan siap cetak.',
    module: 'assessment',
    icon: 'file-text',
    accent: 'emerald',
  },
  {
    slug: 'presentation',
    title: 'Presentation Generator',
    subtitle: 'Slide Presentasi',
    desc: 'Generate outline dan konten presentasi slide PowerPoint-ready.',
    module: 'content',
    icon: 'presentation',
    accent: 'gold',
  },
  {
    slug: 'syllabus',
    title: 'Syllabus Generator',
    subtitle: 'Silabus Kurikulum',
    desc: 'Buat silabus lengkap sesuai kurikulum (Merdeka/K13) dan jenjang madrasah.',
    module: 'content',
    icon: 'book-marked',
    accent: 'gold',
  },
  {
    slug: 'unit-plan',
    title: 'Unit Plan / RPP',
    subtitle: 'Modul Ajar',
    desc: 'Rencana pembelajaran unit (RPP/Modul Ajar) lengkap siap pakai.',
    module: 'content',
    icon: 'book-open',
    accent: 'gold',
  },
  {
    slug: 'academic-content',
    title: 'Academic Content',
    subtitle: 'Konten Akademik',
    desc: 'Konten akademik custom — rangkuman, penjelasan materi, contoh soal.',
    module: 'content',
    icon: 'graduation-cap',
    accent: 'gold',
  },
];

export const findTool = (slug) => TOOLS.find((t) => t.slug === slug);
